# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='websiteorcontact',
            field=models.CharField(default='yournamehere', max_length=100),
        ),
    ]
