# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170915_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='websiteorcontact',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='clubs',
            name='getstarted',
            field=models.CharField(default='How to try it out?', max_length=200),
        ),
        migrations.AddField(
            model_name='clubs',
            name='website',
            field=models.CharField(default='dave@XSport.co.uk', max_length=100),
        ),
    ]
