# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170916_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='contact',
            field=models.EmailField(default='youremail@xname.com', max_length=254),
        ),
    ]
