# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_clubs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='image',
        ),
    ]
