# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170916_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='Event location here', max_length=200),
        ),
    ]
